SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(wildcard verilog/*.v)

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkTopMAC
MODULE   := test_mac

include $(shell cocotb-config --makefiles)/Makefile.sim
